import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/Providers/NextAurhProvider";
import WhatsAppButton from "../../components/WhatsAppButton";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "CARX",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
          <WhatsAppButton></WhatsAppButton>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </NextAuthProvider>
      </body>
    </html>
  );
}
